const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),path=require('path');
const root=path.resolve(__dirname,'..');let checks=0;
function run(name,fn){fn();checks++;console.log('PASS '+name);}
function context(seed={}){const disk=new Map(Object.entries(seed)),ctx={console,crypto:crypto.webcrypto,structuredClone,Date,Set,Map,Event:class{},localStorage:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)},document:{getElementById:()=>null}};ctx.window=ctx;ctx.dispatchEvent=()=>{};vm.createContext(ctx);for(const f of ['storage.js','meals.js','planner.js','nutrition.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);const capture=fs.readFileSync(path.join(root,'capture.js'),'utf8');vm.runInContext(capture.slice(0,capture.indexOf(' const dialog='))+'return {parse,schoolParse,validDate};})();',ctx);return {ctx,disk};}
const {ctx:c,disk}=context(),{MN,ME,PN,NI,QC}=c,date=MN.sessionDate;
MN.update(s=>{s.inventory=['전복','콩나물','어묵'].map((name,i)=>({id:i,name,cat:name==='전복'?'냉동':'냉장'}));s.days[date]??={meals:{}};s.days[date].preferred=['전복','콩나물','어묵'];});
run('Every alternative preserves all three selected ingredients and has at most one soup',()=>{const all=PN.options();assert(all.length>3);for(const p of all){assert.equal(p.covered.length,3);assert.equal(p.uncovered.length,0);assert(p.dishes.filter(x=>/국$|찌개$/.test(x)).length<=1);}assert(new Set(all.map(x=>x.id)).size===all.length);});
run('Unknown priority ingredient is disclosed, never fabricated into a dish',()=>{const s=MN.snapshot();s.days[date].preferred.push('테스트미등록재료');assert(PN.options(date,s).every(x=>x.uncovered.includes('테스트미등록재료')));});
run('Single abalone priority avoids doubling the main ingredient or adding soup to porridge',()=>{const s=MN.snapshot();s.days[date].preferred=['전복'];s.inventory=s.inventory.filter(x=>x.name==='전복');for(const p of PN.options(date,s)){assert(p.dishes.filter(x=>x.includes('전복')).length===1);if(p.dishes.some(x=>x.endsWith('죽')))assert(!p.dishes.some(x=>/국$|찌개$/.test(x)));}});
run('Whole meal selection preserves actual record',()=>{ME.edit(date,'dinner','actual',ME.items('토마토리조또'));PN.choose(date,PN.options()[0].id);assert.equal(ME.title(ME.timeline(date).find(x=>x.slot==='dinner').actual.items),'토마토리조또');});
run('One dish edit preserves sibling IDs, recalculates shopping and thaw tasks',()=>{ME.update(s=>s.days[date].meals.dinner.actual=null);ME.edit(date,'dinner','plan',ME.items('쌀밥 · 전복간장조림 · 콩나물국 · 어묵볶음'));const before=MN.snapshot().days[date].meals.dinner.plan.items,edited=structuredClone(before);edited[1].name='전복버터구이';ME.edit(date,'dinner','plan',edited);const after=MN.snapshot().days[date].meals.dinner.plan.items;assert.equal(after[0].id,before[0].id);assert.equal(after[2].name,before[2].name);const t=ME.tasks();assert(t.some(x=>x.type==='shop'&&x.ingredient==='버터'));assert(!t.some(x=>x.ingredient==='간장'));assert(t.some(x=>x.type==='thaw'&&x.ingredient==='전복'));});
run('Pork soup and tomato risotto classify conservatively and consistently',()=>{for(let i=0;i<3;i++){const n=NI.weekly([{school:'돼지국밥 토마토리조또'}]);for(const key of ['carb','protein','fat','vitamin','mineral'])assert.equal(n.scores[key],1);assert(n.foods.protein.includes('돼지고기'));assert(!n.foods.protein.includes('치즈'));}const tomato=NI.weekly([{school:'토마토리조또'}]);assert.equal(tomato.scores.protein,0);assert.equal(tomato.scores.fat,0);});
run('No pear/radish/seaweed hallucinated from delivery and unrelated words',()=>{const t=NI.tokens('배달 어묵볶음 무침 김치');assert(!t.includes('배'));assert(!t.includes('무'));assert(!t.includes('김'));});
run('Natural language sample produces three clean meal rows',()=>{const p=QC.parse('오늘 아침 돼지국밥 먹었고 간식으로 바나나 먹었어. 저녁은 토마토리조또.',date);assert.equal(p.errors.length,0);assert.equal(p.rows.length,3);assert.equal(p.rows[0].text,'돼지국밥');assert.equal(p.rows[1].text,'바나나');assert.equal(p.rows[2].text,'토마토리조또');});
run('Ambiguous date, missing slot, negation and future inputs are blocked',()=>{for(const s of ['오늘 아침 밥 어제 저녁 국','돼지국밥 먹었어','내일 저녁 국밥','아침 안 먹었어'])assert(QC.parse(s,date).errors.length>0);});
run('Batch school parser supports distant dates and rejects invalid/duplicate dates',()=>{const a=QC.schoolParse('9/22 오전 바나나 / 점심 쌀밥, 소불고기 / 오후 우유\n12/15 사과 | 전복죽 | 고구마',2026);assert.equal(a.errors.length,0);assert.equal(a.rows.length,2);assert.equal(a.rows[1].lunch,'전복죽');assert(QC.schoolParse('2/30 점심 밥',2026).errors.length);assert(QC.schoolParse('9/22 점심 밥\n9/22 점심 국',2026).errors.length);});
run('Actual, institution and future plans remain separate in weekly nutrition',()=>{ME.edit(date,'breakfast','actual',ME.items('돼지국밥'));ME.edit(MN.dateKey(1),'dinner','plan',ME.items('연어구이'));const week=ME.week(date);assert(week.actual.some(x=>x.school.includes('돼지국밥')));assert(!week.actual.some(x=>x.school.includes('연어')));});
run('v20 schema 3 data roundtrip preserves profile inventory plans actual extras school and completion state',()=>{const base=MN.snapshot();base.profile={sex:'여자',birth:'2020-01-01',institutionMeals:'있음'};base.days[date].school='점심 쌀밥';base.days[date].extras={fruit:true,dairy:true};base.prepDone={'existing-task':true};base.days['2026-01-01']={meals:{dinner:{source:'home',plan:{items:[{id:'old','name':'달걀말이'}],confirmed:true},actual:{items:[{id:'actual-old','name':'국밥'}]}}},extras:{fruit:true}};const next=context({'mealnote.state.v2':JSON.stringify(base)}).ctx.MN.snapshot();assert.equal(JSON.stringify(next),JSON.stringify(base));assert.equal(MN.review(JSON.stringify({format:'mealnote-backup',state:base})).schemaVersion,3);});
run('Legacy schema 2 whole-day record is retained without assigning a guessed meal',()=>{const base=MN.snapshot();base.schemaVersion=2;base.days={[date]:{actual:{menu:'돼지국밥 토마토리조또',fruit:true,dairy:false},custom:'전복죽',school:'점심 쌀밥'}};const next=context({'mealnote.state.v2':JSON.stringify(base)}).ctx.MN.snapshot();assert.equal(next.days[date].legacyActual.menu,'돼지국밥 토마토리조또');assert.equal(next.days[date].meals.dinner.actual,null);assert.equal(next.days[date].meals.dinner.plan.items[0].name,'전복죽');});
run('Restore and undo preserve pre-restore state',()=>{const before=MN.snapshot(),restore=structuredClone(before);restore.inventory=[];MN.restore(restore);assert.equal(MN.snapshot().inventory.length,0);MN.undo();assert.equal(MN.snapshot().inventory.length,before.inventory.length);});
run('Storage conflict refuses to overwrite newer data',()=>{const newer=MN.snapshot();newer.revision++;disk.set('mealnote.state.v2',JSON.stringify(newer));assert.throws(()=>MN.update(s=>s.welcome='test'));assert.equal(JSON.parse(disk.get('mealnote.state.v2')).revision,newer.revision);});
console.log(checks+' model tests passed');
